FROM golang:1.23-alpine3.20 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN apk update && apk add --no-cache docker

RUN go build -o myapp ./cmd/scheduler/main.go

CMD ["./myapp"]
